from datetime import date
from typing import List, Optional
from uuid import UUID
from pydantic import BaseModel, Field


class ProjectAnalysisInput(BaseModel):
    project_name: str = Field(..., min_length=2, max_length=150, description="Name of the project")
    description: str = Field(..., min_length=10, description="Detailed project description")
    deadline: Optional[date] = Field(None, description="Project deadline date")


class ModuleSkillRequirement(BaseModel):
    skill_name: str = Field(..., description="Name of the skill required")
    required_level: Optional[str] = Field("Intermediate", description="Required level: Junior, Intermediate, Senior")
    mandatory: bool = Field(True, description="Whether this skill is mandatory or optional")


class ModuleAnalysisSchema(BaseModel):
    module_name: str = Field(..., description="Name of the module, e.g. Frontend, Backend, AI, Testing")
    description: Optional[str] = Field(None, description="Description of the module work")
    estimated_hours: int = Field(..., ge=1, description="Estimated effort in hours")
    priority: str = Field("Medium", description="Priority level: High, Medium, Low")
    skills: List[ModuleSkillRequirement] = Field(..., description="List of required skills for this module")


class ProjectAnalysisResponse(BaseModel):
    modules: List[ModuleAnalysisSchema] = Field(..., min_items=1, description="List of analyzed modules")
    timeline: str = Field(..., description="Suggested timeline summary generated by AI")


class ResourceMatchDetail(BaseModel):
    id: UUID
    fullName: str
    jobTitle: str
    avatarUrl: Optional[str] = None
    matchScore: int = Field(..., ge=0, le=100)
    matchedSkills: List[str] = []
    missingSkills: List[str] = []
    currentProjects: List[str] = []
    assignedHours: float = 0.0
    weeklyAllowedHours: float = 35.0
    utilization: float = 0.0
    availability: float = 35.0


class ModuleRecommendationGroup(BaseModel):
    module_id: int
    module_name: str
    required_skills: List[str]
    exact_matches: List[ResourceMatchDetail] = []
    related_matches: List[ResourceMatchDetail] = []
    transferable_matches: List[ResourceMatchDetail] = []
    upskill_candidates: List[ResourceMatchDetail] = []


class AssignmentRequest(BaseModel):
    module_id: int
    resource_id: UUID
    assignment_type: Optional[str] = Field("standard", description="Type of assignment")


class SubTaskPlan(BaseModel):
    task_name: str = Field(..., description="Name of the subtask")
    description: Optional[str] = Field(None, description="Details of the subtask")
    estimated_hours: int = Field(..., ge=1, description="Estimated hours")
    priority: str = Field("Medium", description="Priority: High, Medium, Low")


class TaskPlan(BaseModel):
    temp_id: str = Field(..., description="A temporary ID to map dependencies, e.g. T1, T2")
    task_name: str = Field(..., description="Name of the task")
    description: Optional[str] = Field(None, description="Details of the task")
    estimated_hours: int = Field(..., ge=1, description="Estimated hours")
    priority: str = Field("Medium", description="Priority: High, Medium, Low")
    depends_on: List[str] = Field(default=[], description="List of temp_ids this task depends on")
    subtasks: List[SubTaskPlan] = Field(default=[], description="Subtasks within this task")


class TaskPlanResponse(BaseModel):
    tasks: List[TaskPlan] = Field(..., description="List of generated tasks with hierarchy and dependencies")


class TaskScheduleRequest(BaseModel):
    task_id: UUID
    resource_id: UUID
    work_date: date
    planned_hours: int
    status: Optional[str] = "planned"


class TaskLogTimeRequest(BaseModel):
    hours_logged: float = Field(..., gt=0.0, description="Hours worked on the task")
    notes: Optional[str] = Field(None, description="Notes about what was completed")


class TaskReassignRequest(BaseModel):
    task_id: UUID
    resource_id: Optional[UUID] = Field(None, description="New resource ID, or null to unassign")

