/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UserReportsRouteImport } from './routes/user.reports'
import { Route as UserProfileRouteImport } from './routes/user.profile'
import { Route as UserPayslipsRouteImport } from './routes/user.payslips'
import { Route as UserCalendarRouteImport } from './routes/user.calendar'
import { Route as UserAnnouncementsRouteImport } from './routes/user.announcements'
import { Route as AdminTimesheetsRouteImport } from './routes/admin.timesheets'
import { Route as AdminSystemAdminsRouteImport } from './routes/admin.system-admins'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminProductivityRouteImport } from './routes/admin.productivity'
import { Route as AdminLeavesRouteImport } from './routes/admin.leaves'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as UserTimesheetsIndexRouteImport } from './routes/user.timesheets.index'
import { Route as UserTasksIndexRouteImport } from './routes/user.tasks.index'
import { Route as UserLeavesIndexRouteImport } from './routes/user.leaves.index'
import { Route as AdminTimesheetsIndexRouteImport } from './routes/admin.timesheets.index'
import { Route as AdminTasksIndexRouteImport } from './routes/admin.tasks.index'
import { Route as AdminResourcesIndexRouteImport } from './routes/admin.resources.index'
import { Route as AdminReportsIndexRouteImport } from './routes/admin.reports.index'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin.projects.index'
import { Route as AdminPayslipsIndexRouteImport } from './routes/admin.payslips.index'
import { Route as AdminClientsIndexRouteImport } from './routes/admin.clients.index'
import { Route as AdminAnnouncementsIndexRouteImport } from './routes/admin.announcements.index'
import { Route as UserTimesheetsNewRouteImport } from './routes/user.timesheets.new'
import { Route as UserTasksIdRouteImport } from './routes/user.tasks.$id'
import { Route as UserLeavesApplyRouteImport } from './routes/user.leaves.apply'
import { Route as AdminTimesheetsIdRouteImport } from './routes/admin.timesheets.$id'
import { Route as AdminTasksNewRouteImport } from './routes/admin.tasks.new'
import { Route as AdminTasksIdRouteImport } from './routes/admin.tasks.$id'
import { Route as AdminResourcesWorkloadRouteImport } from './routes/admin.resources.workload'
import { Route as AdminResourcesPendingRouteImport } from './routes/admin.resources.pending'
import { Route as AdminResourcesIdRouteImport } from './routes/admin.resources.$id'
import { Route as AdminReportsVisaExpiryRouteImport } from './routes/admin.reports.visa-expiry'
import { Route as AdminReportsTimesheetsRouteImport } from './routes/admin.reports.timesheets'
import { Route as AdminReportsProfilesRouteImport } from './routes/admin.reports.profiles'
import { Route as AdminReportsPeriodicTimesheetsRouteImport } from './routes/admin.reports.periodic-timesheets'
import { Route as AdminReportsPassportExpiryRouteImport } from './routes/admin.reports.passport-expiry'
import { Route as AdminReportsOtherDocumentsRouteImport } from './routes/admin.reports.other-documents'
import { Route as AdminReportsLeavesRouteImport } from './routes/admin.reports.leaves'
import { Route as AdminReportsAddressChangeRouteImport } from './routes/admin.reports.address-change'
import { Route as AdminProjectsNewAiRouteImport } from './routes/admin.projects.new-ai'
import { Route as AdminProjectsNewRouteImport } from './routes/admin.projects.new'
import { Route as AdminPayslipsNewRouteImport } from './routes/admin.payslips.new'
import { Route as AdminClientsNewRouteImport } from './routes/admin.clients.new'
import { Route as AdminClientsIdRouteImport } from './routes/admin.clients.$id'
import { Route as AdminAnnouncementsNewRouteImport } from './routes/admin.announcements.new'
import { Route as AdminProjectsIdProgressRouteImport } from './routes/admin.projects.$id.progress'
import { Route as AdminProjectsIdExecutionRouteImport } from './routes/admin.projects.$id.execution'
import { Route as AdminProjectsIdEditRouteImport } from './routes/admin.projects.$id.edit'
import { Route as AdminClientsIdEditRouteImport } from './routes/admin.clients.$id.edit'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UserReportsRoute = UserReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => UserRoute,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRoute,
} as any)
const UserPayslipsRoute = UserPayslipsRouteImport.update({
  id: '/payslips',
  path: '/payslips',
  getParentRoute: () => UserRoute,
} as any)
const UserCalendarRoute = UserCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => UserRoute,
} as any)
const UserAnnouncementsRoute = UserAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => UserRoute,
} as any)
const AdminTimesheetsRoute = AdminTimesheetsRouteImport.update({
  id: '/timesheets',
  path: '/timesheets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemAdminsRoute = AdminSystemAdminsRouteImport.update({
  id: '/system-admins',
  path: '/system-admins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductivityRoute = AdminProductivityRouteImport.update({
  id: '/productivity',
  path: '/productivity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeavesRoute = AdminLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const UserTimesheetsIndexRoute = UserTimesheetsIndexRouteImport.update({
  id: '/timesheets/',
  path: '/timesheets/',
  getParentRoute: () => UserRoute,
} as any)
const UserTasksIndexRoute = UserTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => UserRoute,
} as any)
const UserLeavesIndexRoute = UserLeavesIndexRouteImport.update({
  id: '/leaves/',
  path: '/leaves/',
  getParentRoute: () => UserRoute,
} as any)
const AdminTimesheetsIndexRoute = AdminTimesheetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTimesheetsRoute,
} as any)
const AdminTasksIndexRoute = AdminTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResourcesIndexRoute = AdminResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminReportsRoute,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayslipsIndexRoute = AdminPayslipsIndexRouteImport.update({
  id: '/payslips/',
  path: '/payslips/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsIndexRoute = AdminClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsIndexRoute = AdminAnnouncementsIndexRouteImport.update({
  id: '/announcements/',
  path: '/announcements/',
  getParentRoute: () => AdminRoute,
} as any)
const UserTimesheetsNewRoute = UserTimesheetsNewRouteImport.update({
  id: '/timesheets/new',
  path: '/timesheets/new',
  getParentRoute: () => UserRoute,
} as any)
const UserTasksIdRoute = UserTasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => UserRoute,
} as any)
const UserLeavesApplyRoute = UserLeavesApplyRouteImport.update({
  id: '/leaves/apply',
  path: '/leaves/apply',
  getParentRoute: () => UserRoute,
} as any)
const AdminTimesheetsIdRoute = AdminTimesheetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminTimesheetsRoute,
} as any)
const AdminTasksNewRoute = AdminTasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksIdRoute = AdminTasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResourcesWorkloadRoute = AdminResourcesWorkloadRouteImport.update({
  id: '/resources/workload',
  path: '/resources/workload',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResourcesPendingRoute = AdminResourcesPendingRouteImport.update({
  id: '/resources/pending',
  path: '/resources/pending',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResourcesIdRoute = AdminResourcesIdRouteImport.update({
  id: '/resources/$id',
  path: '/resources/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsVisaExpiryRoute = AdminReportsVisaExpiryRouteImport.update({
  id: '/visa-expiry',
  path: '/visa-expiry',
  getParentRoute: () => AdminReportsRoute,
} as any)
const AdminReportsTimesheetsRoute = AdminReportsTimesheetsRouteImport.update({
  id: '/timesheets',
  path: '/timesheets',
  getParentRoute: () => AdminReportsRoute,
} as any)
const AdminReportsProfilesRoute = AdminReportsProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AdminReportsRoute,
} as any)
const AdminReportsPeriodicTimesheetsRoute =
  AdminReportsPeriodicTimesheetsRouteImport.update({
    id: '/periodic-timesheets',
    path: '/periodic-timesheets',
    getParentRoute: () => AdminReportsRoute,
  } as any)
const AdminReportsPassportExpiryRoute =
  AdminReportsPassportExpiryRouteImport.update({
    id: '/passport-expiry',
    path: '/passport-expiry',
    getParentRoute: () => AdminReportsRoute,
  } as any)
const AdminReportsOtherDocumentsRoute =
  AdminReportsOtherDocumentsRouteImport.update({
    id: '/other-documents',
    path: '/other-documents',
    getParentRoute: () => AdminReportsRoute,
  } as any)
const AdminReportsLeavesRoute = AdminReportsLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => AdminReportsRoute,
} as any)
const AdminReportsAddressChangeRoute =
  AdminReportsAddressChangeRouteImport.update({
    id: '/address-change',
    path: '/address-change',
    getParentRoute: () => AdminReportsRoute,
  } as any)
const AdminProjectsNewAiRoute = AdminProjectsNewAiRouteImport.update({
  id: '/projects/new-ai',
  path: '/projects/new-ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsNewRoute = AdminProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayslipsNewRoute = AdminPayslipsNewRouteImport.update({
  id: '/payslips/new',
  path: '/payslips/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsNewRoute = AdminClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsIdRoute = AdminClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsNewRoute = AdminAnnouncementsNewRouteImport.update({
  id: '/announcements/new',
  path: '/announcements/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsIdProgressRoute = AdminProjectsIdProgressRouteImport.update({
  id: '/projects/$id/progress',
  path: '/projects/$id/progress',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsIdExecutionRoute =
  AdminProjectsIdExecutionRouteImport.update({
    id: '/projects/$id/execution',
    path: '/projects/$id/execution',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminProjectsIdEditRoute = AdminProjectsIdEditRouteImport.update({
  id: '/projects/$id/edit',
  path: '/projects/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsIdEditRoute = AdminClientsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminClientsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/user': typeof UserRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/leaves': typeof AdminLeavesRoute
  '/admin/productivity': typeof AdminProductivityRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRouteWithChildren
  '/admin/system-admins': typeof AdminSystemAdminsRoute
  '/admin/timesheets': typeof AdminTimesheetsRouteWithChildren
  '/user/announcements': typeof UserAnnouncementsRoute
  '/user/calendar': typeof UserCalendarRoute
  '/user/payslips': typeof UserPayslipsRoute
  '/user/profile': typeof UserProfileRoute
  '/user/reports': typeof UserReportsRoute
  '/admin/': typeof AdminIndexRoute
  '/user/': typeof UserIndexRoute
  '/admin/announcements/new': typeof AdminAnnouncementsNewRoute
  '/admin/clients/$id': typeof AdminClientsIdRouteWithChildren
  '/admin/clients/new': typeof AdminClientsNewRoute
  '/admin/payslips/new': typeof AdminPayslipsNewRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/projects/new-ai': typeof AdminProjectsNewAiRoute
  '/admin/reports/address-change': typeof AdminReportsAddressChangeRoute
  '/admin/reports/leaves': typeof AdminReportsLeavesRoute
  '/admin/reports/other-documents': typeof AdminReportsOtherDocumentsRoute
  '/admin/reports/passport-expiry': typeof AdminReportsPassportExpiryRoute
  '/admin/reports/periodic-timesheets': typeof AdminReportsPeriodicTimesheetsRoute
  '/admin/reports/profiles': typeof AdminReportsProfilesRoute
  '/admin/reports/timesheets': typeof AdminReportsTimesheetsRoute
  '/admin/reports/visa-expiry': typeof AdminReportsVisaExpiryRoute
  '/admin/resources/$id': typeof AdminResourcesIdRoute
  '/admin/resources/pending': typeof AdminResourcesPendingRoute
  '/admin/resources/workload': typeof AdminResourcesWorkloadRoute
  '/admin/tasks/$id': typeof AdminTasksIdRoute
  '/admin/tasks/new': typeof AdminTasksNewRoute
  '/admin/timesheets/$id': typeof AdminTimesheetsIdRoute
  '/user/leaves/apply': typeof UserLeavesApplyRoute
  '/user/tasks/$id': typeof UserTasksIdRoute
  '/user/timesheets/new': typeof UserTimesheetsNewRoute
  '/admin/announcements/': typeof AdminAnnouncementsIndexRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/payslips/': typeof AdminPayslipsIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/resources/': typeof AdminResourcesIndexRoute
  '/admin/tasks/': typeof AdminTasksIndexRoute
  '/admin/timesheets/': typeof AdminTimesheetsIndexRoute
  '/user/leaves/': typeof UserLeavesIndexRoute
  '/user/tasks/': typeof UserTasksIndexRoute
  '/user/timesheets/': typeof UserTimesheetsIndexRoute
  '/admin/clients/$id/edit': typeof AdminClientsIdEditRoute
  '/admin/projects/$id/edit': typeof AdminProjectsIdEditRoute
  '/admin/projects/$id/execution': typeof AdminProjectsIdExecutionRoute
  '/admin/projects/$id/progress': typeof AdminProjectsIdProgressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/leaves': typeof AdminLeavesRoute
  '/admin/productivity': typeof AdminProductivityRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/system-admins': typeof AdminSystemAdminsRoute
  '/user/announcements': typeof UserAnnouncementsRoute
  '/user/calendar': typeof UserCalendarRoute
  '/user/payslips': typeof UserPayslipsRoute
  '/user/profile': typeof UserProfileRoute
  '/user/reports': typeof UserReportsRoute
  '/admin': typeof AdminIndexRoute
  '/user': typeof UserIndexRoute
  '/admin/announcements/new': typeof AdminAnnouncementsNewRoute
  '/admin/clients/$id': typeof AdminClientsIdRouteWithChildren
  '/admin/clients/new': typeof AdminClientsNewRoute
  '/admin/payslips/new': typeof AdminPayslipsNewRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/projects/new-ai': typeof AdminProjectsNewAiRoute
  '/admin/reports/address-change': typeof AdminReportsAddressChangeRoute
  '/admin/reports/leaves': typeof AdminReportsLeavesRoute
  '/admin/reports/other-documents': typeof AdminReportsOtherDocumentsRoute
  '/admin/reports/passport-expiry': typeof AdminReportsPassportExpiryRoute
  '/admin/reports/periodic-timesheets': typeof AdminReportsPeriodicTimesheetsRoute
  '/admin/reports/profiles': typeof AdminReportsProfilesRoute
  '/admin/reports/timesheets': typeof AdminReportsTimesheetsRoute
  '/admin/reports/visa-expiry': typeof AdminReportsVisaExpiryRoute
  '/admin/resources/$id': typeof AdminResourcesIdRoute
  '/admin/resources/pending': typeof AdminResourcesPendingRoute
  '/admin/resources/workload': typeof AdminResourcesWorkloadRoute
  '/admin/tasks/$id': typeof AdminTasksIdRoute
  '/admin/tasks/new': typeof AdminTasksNewRoute
  '/admin/timesheets/$id': typeof AdminTimesheetsIdRoute
  '/user/leaves/apply': typeof UserLeavesApplyRoute
  '/user/tasks/$id': typeof UserTasksIdRoute
  '/user/timesheets/new': typeof UserTimesheetsNewRoute
  '/admin/announcements': typeof AdminAnnouncementsIndexRoute
  '/admin/clients': typeof AdminClientsIndexRoute
  '/admin/payslips': typeof AdminPayslipsIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/admin/resources': typeof AdminResourcesIndexRoute
  '/admin/tasks': typeof AdminTasksIndexRoute
  '/admin/timesheets': typeof AdminTimesheetsIndexRoute
  '/user/leaves': typeof UserLeavesIndexRoute
  '/user/tasks': typeof UserTasksIndexRoute
  '/user/timesheets': typeof UserTimesheetsIndexRoute
  '/admin/clients/$id/edit': typeof AdminClientsIdEditRoute
  '/admin/projects/$id/edit': typeof AdminProjectsIdEditRoute
  '/admin/projects/$id/execution': typeof AdminProjectsIdExecutionRoute
  '/admin/projects/$id/progress': typeof AdminProjectsIdProgressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/user': typeof UserRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/leaves': typeof AdminLeavesRoute
  '/admin/productivity': typeof AdminProductivityRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRouteWithChildren
  '/admin/system-admins': typeof AdminSystemAdminsRoute
  '/admin/timesheets': typeof AdminTimesheetsRouteWithChildren
  '/user/announcements': typeof UserAnnouncementsRoute
  '/user/calendar': typeof UserCalendarRoute
  '/user/payslips': typeof UserPayslipsRoute
  '/user/profile': typeof UserProfileRoute
  '/user/reports': typeof UserReportsRoute
  '/admin/': typeof AdminIndexRoute
  '/user/': typeof UserIndexRoute
  '/admin/announcements/new': typeof AdminAnnouncementsNewRoute
  '/admin/clients/$id': typeof AdminClientsIdRouteWithChildren
  '/admin/clients/new': typeof AdminClientsNewRoute
  '/admin/payslips/new': typeof AdminPayslipsNewRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/projects/new-ai': typeof AdminProjectsNewAiRoute
  '/admin/reports/address-change': typeof AdminReportsAddressChangeRoute
  '/admin/reports/leaves': typeof AdminReportsLeavesRoute
  '/admin/reports/other-documents': typeof AdminReportsOtherDocumentsRoute
  '/admin/reports/passport-expiry': typeof AdminReportsPassportExpiryRoute
  '/admin/reports/periodic-timesheets': typeof AdminReportsPeriodicTimesheetsRoute
  '/admin/reports/profiles': typeof AdminReportsProfilesRoute
  '/admin/reports/timesheets': typeof AdminReportsTimesheetsRoute
  '/admin/reports/visa-expiry': typeof AdminReportsVisaExpiryRoute
  '/admin/resources/$id': typeof AdminResourcesIdRoute
  '/admin/resources/pending': typeof AdminResourcesPendingRoute
  '/admin/resources/workload': typeof AdminResourcesWorkloadRoute
  '/admin/tasks/$id': typeof AdminTasksIdRoute
  '/admin/tasks/new': typeof AdminTasksNewRoute
  '/admin/timesheets/$id': typeof AdminTimesheetsIdRoute
  '/user/leaves/apply': typeof UserLeavesApplyRoute
  '/user/tasks/$id': typeof UserTasksIdRoute
  '/user/timesheets/new': typeof UserTimesheetsNewRoute
  '/admin/announcements/': typeof AdminAnnouncementsIndexRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/payslips/': typeof AdminPayslipsIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/resources/': typeof AdminResourcesIndexRoute
  '/admin/tasks/': typeof AdminTasksIndexRoute
  '/admin/timesheets/': typeof AdminTimesheetsIndexRoute
  '/user/leaves/': typeof UserLeavesIndexRoute
  '/user/tasks/': typeof UserTasksIndexRoute
  '/user/timesheets/': typeof UserTimesheetsIndexRoute
  '/admin/clients/$id/edit': typeof AdminClientsIdEditRoute
  '/admin/projects/$id/edit': typeof AdminProjectsIdEditRoute
  '/admin/projects/$id/execution': typeof AdminProjectsIdExecutionRoute
  '/admin/projects/$id/progress': typeof AdminProjectsIdProgressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/user'
    | '/admin/analytics'
    | '/admin/leaves'
    | '/admin/productivity'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/system-admins'
    | '/admin/timesheets'
    | '/user/announcements'
    | '/user/calendar'
    | '/user/payslips'
    | '/user/profile'
    | '/user/reports'
    | '/admin/'
    | '/user/'
    | '/admin/announcements/new'
    | '/admin/clients/$id'
    | '/admin/clients/new'
    | '/admin/payslips/new'
    | '/admin/projects/new'
    | '/admin/projects/new-ai'
    | '/admin/reports/address-change'
    | '/admin/reports/leaves'
    | '/admin/reports/other-documents'
    | '/admin/reports/passport-expiry'
    | '/admin/reports/periodic-timesheets'
    | '/admin/reports/profiles'
    | '/admin/reports/timesheets'
    | '/admin/reports/visa-expiry'
    | '/admin/resources/$id'
    | '/admin/resources/pending'
    | '/admin/resources/workload'
    | '/admin/tasks/$id'
    | '/admin/tasks/new'
    | '/admin/timesheets/$id'
    | '/user/leaves/apply'
    | '/user/tasks/$id'
    | '/user/timesheets/new'
    | '/admin/announcements/'
    | '/admin/clients/'
    | '/admin/payslips/'
    | '/admin/projects/'
    | '/admin/reports/'
    | '/admin/resources/'
    | '/admin/tasks/'
    | '/admin/timesheets/'
    | '/user/leaves/'
    | '/user/tasks/'
    | '/user/timesheets/'
    | '/admin/clients/$id/edit'
    | '/admin/projects/$id/edit'
    | '/admin/projects/$id/execution'
    | '/admin/projects/$id/progress'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/analytics'
    | '/admin/leaves'
    | '/admin/productivity'
    | '/admin/profile'
    | '/admin/system-admins'
    | '/user/announcements'
    | '/user/calendar'
    | '/user/payslips'
    | '/user/profile'
    | '/user/reports'
    | '/admin'
    | '/user'
    | '/admin/announcements/new'
    | '/admin/clients/$id'
    | '/admin/clients/new'
    | '/admin/payslips/new'
    | '/admin/projects/new'
    | '/admin/projects/new-ai'
    | '/admin/reports/address-change'
    | '/admin/reports/leaves'
    | '/admin/reports/other-documents'
    | '/admin/reports/passport-expiry'
    | '/admin/reports/periodic-timesheets'
    | '/admin/reports/profiles'
    | '/admin/reports/timesheets'
    | '/admin/reports/visa-expiry'
    | '/admin/resources/$id'
    | '/admin/resources/pending'
    | '/admin/resources/workload'
    | '/admin/tasks/$id'
    | '/admin/tasks/new'
    | '/admin/timesheets/$id'
    | '/user/leaves/apply'
    | '/user/tasks/$id'
    | '/user/timesheets/new'
    | '/admin/announcements'
    | '/admin/clients'
    | '/admin/payslips'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/resources'
    | '/admin/tasks'
    | '/admin/timesheets'
    | '/user/leaves'
    | '/user/tasks'
    | '/user/timesheets'
    | '/admin/clients/$id/edit'
    | '/admin/projects/$id/edit'
    | '/admin/projects/$id/execution'
    | '/admin/projects/$id/progress'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/user'
    | '/admin/analytics'
    | '/admin/leaves'
    | '/admin/productivity'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/system-admins'
    | '/admin/timesheets'
    | '/user/announcements'
    | '/user/calendar'
    | '/user/payslips'
    | '/user/profile'
    | '/user/reports'
    | '/admin/'
    | '/user/'
    | '/admin/announcements/new'
    | '/admin/clients/$id'
    | '/admin/clients/new'
    | '/admin/payslips/new'
    | '/admin/projects/new'
    | '/admin/projects/new-ai'
    | '/admin/reports/address-change'
    | '/admin/reports/leaves'
    | '/admin/reports/other-documents'
    | '/admin/reports/passport-expiry'
    | '/admin/reports/periodic-timesheets'
    | '/admin/reports/profiles'
    | '/admin/reports/timesheets'
    | '/admin/reports/visa-expiry'
    | '/admin/resources/$id'
    | '/admin/resources/pending'
    | '/admin/resources/workload'
    | '/admin/tasks/$id'
    | '/admin/tasks/new'
    | '/admin/timesheets/$id'
    | '/user/leaves/apply'
    | '/user/tasks/$id'
    | '/user/timesheets/new'
    | '/admin/announcements/'
    | '/admin/clients/'
    | '/admin/payslips/'
    | '/admin/projects/'
    | '/admin/reports/'
    | '/admin/resources/'
    | '/admin/tasks/'
    | '/admin/timesheets/'
    | '/user/leaves/'
    | '/user/tasks/'
    | '/user/timesheets/'
    | '/admin/clients/$id/edit'
    | '/admin/projects/$id/edit'
    | '/admin/projects/$id/execution'
    | '/admin/projects/$id/progress'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  UserRoute: typeof UserRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/user/reports': {
      id: '/user/reports'
      path: '/reports'
      fullPath: '/user/reports'
      preLoaderRoute: typeof UserReportsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/payslips': {
      id: '/user/payslips'
      path: '/payslips'
      fullPath: '/user/payslips'
      preLoaderRoute: typeof UserPayslipsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/calendar': {
      id: '/user/calendar'
      path: '/calendar'
      fullPath: '/user/calendar'
      preLoaderRoute: typeof UserCalendarRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/announcements': {
      id: '/user/announcements'
      path: '/announcements'
      fullPath: '/user/announcements'
      preLoaderRoute: typeof UserAnnouncementsRouteImport
      parentRoute: typeof UserRoute
    }
    '/admin/timesheets': {
      id: '/admin/timesheets'
      path: '/timesheets'
      fullPath: '/admin/timesheets'
      preLoaderRoute: typeof AdminTimesheetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system-admins': {
      id: '/admin/system-admins'
      path: '/system-admins'
      fullPath: '/admin/system-admins'
      preLoaderRoute: typeof AdminSystemAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/productivity': {
      id: '/admin/productivity'
      path: '/productivity'
      fullPath: '/admin/productivity'
      preLoaderRoute: typeof AdminProductivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leaves': {
      id: '/admin/leaves'
      path: '/leaves'
      fullPath: '/admin/leaves'
      preLoaderRoute: typeof AdminLeavesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/user/timesheets/': {
      id: '/user/timesheets/'
      path: '/timesheets'
      fullPath: '/user/timesheets/'
      preLoaderRoute: typeof UserTimesheetsIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/tasks/': {
      id: '/user/tasks/'
      path: '/tasks'
      fullPath: '/user/tasks/'
      preLoaderRoute: typeof UserTasksIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/leaves/': {
      id: '/user/leaves/'
      path: '/leaves'
      fullPath: '/user/leaves/'
      preLoaderRoute: typeof UserLeavesIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/admin/timesheets/': {
      id: '/admin/timesheets/'
      path: '/'
      fullPath: '/admin/timesheets/'
      preLoaderRoute: typeof AdminTimesheetsIndexRouteImport
      parentRoute: typeof AdminTimesheetsRoute
    }
    '/admin/tasks/': {
      id: '/admin/tasks/'
      path: '/tasks'
      fullPath: '/admin/tasks/'
      preLoaderRoute: typeof AdminTasksIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resources/': {
      id: '/admin/resources/'
      path: '/resources'
      fullPath: '/admin/resources/'
      preLoaderRoute: typeof AdminResourcesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports/': {
      id: '/admin/reports/'
      path: '/'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof AdminReportsRoute
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payslips/': {
      id: '/admin/payslips/'
      path: '/payslips'
      fullPath: '/admin/payslips/'
      preLoaderRoute: typeof AdminPayslipsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/': {
      id: '/admin/clients/'
      path: '/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AdminClientsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements/': {
      id: '/admin/announcements/'
      path: '/announcements'
      fullPath: '/admin/announcements/'
      preLoaderRoute: typeof AdminAnnouncementsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/user/timesheets/new': {
      id: '/user/timesheets/new'
      path: '/timesheets/new'
      fullPath: '/user/timesheets/new'
      preLoaderRoute: typeof UserTimesheetsNewRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/tasks/$id': {
      id: '/user/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/user/tasks/$id'
      preLoaderRoute: typeof UserTasksIdRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/leaves/apply': {
      id: '/user/leaves/apply'
      path: '/leaves/apply'
      fullPath: '/user/leaves/apply'
      preLoaderRoute: typeof UserLeavesApplyRouteImport
      parentRoute: typeof UserRoute
    }
    '/admin/timesheets/$id': {
      id: '/admin/timesheets/$id'
      path: '/$id'
      fullPath: '/admin/timesheets/$id'
      preLoaderRoute: typeof AdminTimesheetsIdRouteImport
      parentRoute: typeof AdminTimesheetsRoute
    }
    '/admin/tasks/new': {
      id: '/admin/tasks/new'
      path: '/tasks/new'
      fullPath: '/admin/tasks/new'
      preLoaderRoute: typeof AdminTasksNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tasks/$id': {
      id: '/admin/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/admin/tasks/$id'
      preLoaderRoute: typeof AdminTasksIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resources/workload': {
      id: '/admin/resources/workload'
      path: '/resources/workload'
      fullPath: '/admin/resources/workload'
      preLoaderRoute: typeof AdminResourcesWorkloadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resources/pending': {
      id: '/admin/resources/pending'
      path: '/resources/pending'
      fullPath: '/admin/resources/pending'
      preLoaderRoute: typeof AdminResourcesPendingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resources/$id': {
      id: '/admin/resources/$id'
      path: '/resources/$id'
      fullPath: '/admin/resources/$id'
      preLoaderRoute: typeof AdminResourcesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports/visa-expiry': {
      id: '/admin/reports/visa-expiry'
      path: '/visa-expiry'
      fullPath: '/admin/reports/visa-expiry'
      preLoaderRoute: typeof AdminReportsVisaExpiryRouteImport
      parentRoute: typeof AdminReportsRoute
    }
    '/admin/reports/timesheets': {
      id: '/admin/reports/timesheets'
      path: '/timesheets'
      fullPath: '/admin/reports/timesheets'
      preLoaderRoute: typeof AdminReportsTimesheetsRouteImport
      parentRoute: typeof AdminReportsRoute
    }
    '/admin/reports/profiles': {
      id: '/admin/reports/profiles'
      path: '/profiles'
      fullPath: '/admin/reports/profiles'
      preLoaderRoute: typeof AdminReportsProfilesRouteImport
      parentRoute: typeof AdminReportsRoute
    }
    '/admin/reports/periodic-timesheets': {
      id: '/admin/reports/periodic-timesheets'
      path: '/periodic-timesheets'
      fullPath: '/admin/reports/periodic-timesheets'
      preLoaderRoute: typeof AdminReportsPeriodicTimesheetsRouteImport
      parentRoute: typeof AdminReportsRoute
    }
    '/admin/reports/passport-expiry': {
      id: '/admin/reports/passport-expiry'
      path: '/passport-expiry'
      fullPath: '/admin/reports/passport-expiry'
      preLoaderRoute: typeof AdminReportsPassportExpiryRouteImport
      parentRoute: typeof AdminReportsRoute
    }
    '/admin/reports/other-documents': {
      id: '/admin/reports/other-documents'
      path: '/other-documents'
      fullPath: '/admin/reports/other-documents'
      preLoaderRoute: typeof AdminReportsOtherDocumentsRouteImport
      parentRoute: typeof AdminReportsRoute
    }
    '/admin/reports/leaves': {
      id: '/admin/reports/leaves'
      path: '/leaves'
      fullPath: '/admin/reports/leaves'
      preLoaderRoute: typeof AdminReportsLeavesRouteImport
      parentRoute: typeof AdminReportsRoute
    }
    '/admin/reports/address-change': {
      id: '/admin/reports/address-change'
      path: '/address-change'
      fullPath: '/admin/reports/address-change'
      preLoaderRoute: typeof AdminReportsAddressChangeRouteImport
      parentRoute: typeof AdminReportsRoute
    }
    '/admin/projects/new-ai': {
      id: '/admin/projects/new-ai'
      path: '/projects/new-ai'
      fullPath: '/admin/projects/new-ai'
      preLoaderRoute: typeof AdminProjectsNewAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects/new': {
      id: '/admin/projects/new'
      path: '/projects/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AdminProjectsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payslips/new': {
      id: '/admin/payslips/new'
      path: '/payslips/new'
      fullPath: '/admin/payslips/new'
      preLoaderRoute: typeof AdminPayslipsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/new': {
      id: '/admin/clients/new'
      path: '/clients/new'
      fullPath: '/admin/clients/new'
      preLoaderRoute: typeof AdminClientsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/$id': {
      id: '/admin/clients/$id'
      path: '/clients/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AdminClientsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements/new': {
      id: '/admin/announcements/new'
      path: '/announcements/new'
      fullPath: '/admin/announcements/new'
      preLoaderRoute: typeof AdminAnnouncementsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects/$id/progress': {
      id: '/admin/projects/$id/progress'
      path: '/projects/$id/progress'
      fullPath: '/admin/projects/$id/progress'
      preLoaderRoute: typeof AdminProjectsIdProgressRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects/$id/execution': {
      id: '/admin/projects/$id/execution'
      path: '/projects/$id/execution'
      fullPath: '/admin/projects/$id/execution'
      preLoaderRoute: typeof AdminProjectsIdExecutionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects/$id/edit': {
      id: '/admin/projects/$id/edit'
      path: '/projects/$id/edit'
      fullPath: '/admin/projects/$id/edit'
      preLoaderRoute: typeof AdminProjectsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/$id/edit': {
      id: '/admin/clients/$id/edit'
      path: '/edit'
      fullPath: '/admin/clients/$id/edit'
      preLoaderRoute: typeof AdminClientsIdEditRouteImport
      parentRoute: typeof AdminClientsIdRoute
    }
  }
}

interface AdminReportsRouteChildren {
  AdminReportsAddressChangeRoute: typeof AdminReportsAddressChangeRoute
  AdminReportsLeavesRoute: typeof AdminReportsLeavesRoute
  AdminReportsOtherDocumentsRoute: typeof AdminReportsOtherDocumentsRoute
  AdminReportsPassportExpiryRoute: typeof AdminReportsPassportExpiryRoute
  AdminReportsPeriodicTimesheetsRoute: typeof AdminReportsPeriodicTimesheetsRoute
  AdminReportsProfilesRoute: typeof AdminReportsProfilesRoute
  AdminReportsTimesheetsRoute: typeof AdminReportsTimesheetsRoute
  AdminReportsVisaExpiryRoute: typeof AdminReportsVisaExpiryRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
}

const AdminReportsRouteChildren: AdminReportsRouteChildren = {
  AdminReportsAddressChangeRoute: AdminReportsAddressChangeRoute,
  AdminReportsLeavesRoute: AdminReportsLeavesRoute,
  AdminReportsOtherDocumentsRoute: AdminReportsOtherDocumentsRoute,
  AdminReportsPassportExpiryRoute: AdminReportsPassportExpiryRoute,
  AdminReportsPeriodicTimesheetsRoute: AdminReportsPeriodicTimesheetsRoute,
  AdminReportsProfilesRoute: AdminReportsProfilesRoute,
  AdminReportsTimesheetsRoute: AdminReportsTimesheetsRoute,
  AdminReportsVisaExpiryRoute: AdminReportsVisaExpiryRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
}

const AdminReportsRouteWithChildren = AdminReportsRoute._addFileChildren(
  AdminReportsRouteChildren,
)

interface AdminTimesheetsRouteChildren {
  AdminTimesheetsIdRoute: typeof AdminTimesheetsIdRoute
  AdminTimesheetsIndexRoute: typeof AdminTimesheetsIndexRoute
}

const AdminTimesheetsRouteChildren: AdminTimesheetsRouteChildren = {
  AdminTimesheetsIdRoute: AdminTimesheetsIdRoute,
  AdminTimesheetsIndexRoute: AdminTimesheetsIndexRoute,
}

const AdminTimesheetsRouteWithChildren = AdminTimesheetsRoute._addFileChildren(
  AdminTimesheetsRouteChildren,
)

interface AdminClientsIdRouteChildren {
  AdminClientsIdEditRoute: typeof AdminClientsIdEditRoute
}

const AdminClientsIdRouteChildren: AdminClientsIdRouteChildren = {
  AdminClientsIdEditRoute: AdminClientsIdEditRoute,
}

const AdminClientsIdRouteWithChildren = AdminClientsIdRoute._addFileChildren(
  AdminClientsIdRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminLeavesRoute: typeof AdminLeavesRoute
  AdminProductivityRoute: typeof AdminProductivityRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReportsRoute: typeof AdminReportsRouteWithChildren
  AdminSystemAdminsRoute: typeof AdminSystemAdminsRoute
  AdminTimesheetsRoute: typeof AdminTimesheetsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAnnouncementsNewRoute: typeof AdminAnnouncementsNewRoute
  AdminClientsIdRoute: typeof AdminClientsIdRouteWithChildren
  AdminClientsNewRoute: typeof AdminClientsNewRoute
  AdminPayslipsNewRoute: typeof AdminPayslipsNewRoute
  AdminProjectsNewRoute: typeof AdminProjectsNewRoute
  AdminProjectsNewAiRoute: typeof AdminProjectsNewAiRoute
  AdminResourcesIdRoute: typeof AdminResourcesIdRoute
  AdminResourcesPendingRoute: typeof AdminResourcesPendingRoute
  AdminResourcesWorkloadRoute: typeof AdminResourcesWorkloadRoute
  AdminTasksIdRoute: typeof AdminTasksIdRoute
  AdminTasksNewRoute: typeof AdminTasksNewRoute
  AdminAnnouncementsIndexRoute: typeof AdminAnnouncementsIndexRoute
  AdminClientsIndexRoute: typeof AdminClientsIndexRoute
  AdminPayslipsIndexRoute: typeof AdminPayslipsIndexRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
  AdminResourcesIndexRoute: typeof AdminResourcesIndexRoute
  AdminTasksIndexRoute: typeof AdminTasksIndexRoute
  AdminProjectsIdEditRoute: typeof AdminProjectsIdEditRoute
  AdminProjectsIdExecutionRoute: typeof AdminProjectsIdExecutionRoute
  AdminProjectsIdProgressRoute: typeof AdminProjectsIdProgressRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminLeavesRoute: AdminLeavesRoute,
  AdminProductivityRoute: AdminProductivityRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReportsRoute: AdminReportsRouteWithChildren,
  AdminSystemAdminsRoute: AdminSystemAdminsRoute,
  AdminTimesheetsRoute: AdminTimesheetsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminAnnouncementsNewRoute: AdminAnnouncementsNewRoute,
  AdminClientsIdRoute: AdminClientsIdRouteWithChildren,
  AdminClientsNewRoute: AdminClientsNewRoute,
  AdminPayslipsNewRoute: AdminPayslipsNewRoute,
  AdminProjectsNewRoute: AdminProjectsNewRoute,
  AdminProjectsNewAiRoute: AdminProjectsNewAiRoute,
  AdminResourcesIdRoute: AdminResourcesIdRoute,
  AdminResourcesPendingRoute: AdminResourcesPendingRoute,
  AdminResourcesWorkloadRoute: AdminResourcesWorkloadRoute,
  AdminTasksIdRoute: AdminTasksIdRoute,
  AdminTasksNewRoute: AdminTasksNewRoute,
  AdminAnnouncementsIndexRoute: AdminAnnouncementsIndexRoute,
  AdminClientsIndexRoute: AdminClientsIndexRoute,
  AdminPayslipsIndexRoute: AdminPayslipsIndexRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
  AdminResourcesIndexRoute: AdminResourcesIndexRoute,
  AdminTasksIndexRoute: AdminTasksIndexRoute,
  AdminProjectsIdEditRoute: AdminProjectsIdEditRoute,
  AdminProjectsIdExecutionRoute: AdminProjectsIdExecutionRoute,
  AdminProjectsIdProgressRoute: AdminProjectsIdProgressRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface UserRouteChildren {
  UserAnnouncementsRoute: typeof UserAnnouncementsRoute
  UserCalendarRoute: typeof UserCalendarRoute
  UserPayslipsRoute: typeof UserPayslipsRoute
  UserProfileRoute: typeof UserProfileRoute
  UserReportsRoute: typeof UserReportsRoute
  UserIndexRoute: typeof UserIndexRoute
  UserLeavesApplyRoute: typeof UserLeavesApplyRoute
  UserTasksIdRoute: typeof UserTasksIdRoute
  UserTimesheetsNewRoute: typeof UserTimesheetsNewRoute
  UserLeavesIndexRoute: typeof UserLeavesIndexRoute
  UserTasksIndexRoute: typeof UserTasksIndexRoute
  UserTimesheetsIndexRoute: typeof UserTimesheetsIndexRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserAnnouncementsRoute: UserAnnouncementsRoute,
  UserCalendarRoute: UserCalendarRoute,
  UserPayslipsRoute: UserPayslipsRoute,
  UserProfileRoute: UserProfileRoute,
  UserReportsRoute: UserReportsRoute,
  UserIndexRoute: UserIndexRoute,
  UserLeavesApplyRoute: UserLeavesApplyRoute,
  UserTasksIdRoute: UserTasksIdRoute,
  UserTimesheetsNewRoute: UserTimesheetsNewRoute,
  UserLeavesIndexRoute: UserLeavesIndexRoute,
  UserTasksIndexRoute: UserTasksIndexRoute,
  UserTimesheetsIndexRoute: UserTimesheetsIndexRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  UserRoute: UserRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
