/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminTimesheetsRouteImport } from './routes/admin.timesheets'
import { Route as AdminTasksRouteImport } from './routes/admin.tasks'
import { Route as AdminResourcesRouteImport } from './routes/admin.resources'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminTasksNewRouteImport } from './routes/admin.tasks.new'
import { Route as AdminTasksIdRouteImport } from './routes/admin.tasks.$id'
import { Route as AdminResourcesPendingRouteImport } from './routes/admin.resources.pending'
import { Route as AdminResourcesIdRouteImport } from './routes/admin.resources.$id'
import { Route as AdminProjectsNewRouteImport } from './routes/admin.projects.new'
import { Route as AdminClientsNewRouteImport } from './routes/admin.clients.new'
import { Route as AdminClientsRouteImport } from './routes/admin.clients.'
import { Route as AdminProjectsIdEditRouteImport } from './routes/admin.projects.$id.edit'
import { Route as AdminClientsIdEditRouteImport } from './routes/admin.clients.$id.edit'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTimesheetsRoute = AdminTimesheetsRouteImport.update({
  id: '/timesheets',
  path: '/timesheets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResourcesRoute = AdminResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksNewRoute = AdminTasksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminTasksRoute,
} as any)
const AdminTasksIdRoute = AdminTasksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminTasksRoute,
} as any)
const AdminResourcesPendingRoute = AdminResourcesPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AdminResourcesRoute,
} as any)
const AdminResourcesIdRoute = AdminResourcesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminResourcesRoute,
} as any)
const AdminProjectsNewRoute = AdminProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProjectsRoute,
} as any)
const AdminClientsNewRoute = AdminClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminClientsRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminClientsRoute,
} as any)
const AdminProjectsIdEditRoute = AdminProjectsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminProjectsRoute,
} as any)
const AdminClientsIdEditRoute = AdminClientsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/user': typeof UserRoute
  '/admin/clients': typeof AdminClientsRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/resources': typeof AdminResourcesRouteWithChildren
  '/admin/tasks': typeof AdminTasksRouteWithChildren
  '/admin/timesheets': typeof AdminTimesheetsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/clients/': typeof AdminClientsRoute
  '/admin/clients/new': typeof AdminClientsNewRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/resources/$id': typeof AdminResourcesIdRoute
  '/admin/resources/pending': typeof AdminResourcesPendingRoute
  '/admin/tasks/$id': typeof AdminTasksIdRoute
  '/admin/tasks/new': typeof AdminTasksNewRoute
  '/admin/clients/$id/edit': typeof AdminClientsIdEditRoute
  '/admin/projects/$id/edit': typeof AdminProjectsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/user': typeof UserRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/resources': typeof AdminResourcesRouteWithChildren
  '/admin/tasks': typeof AdminTasksRouteWithChildren
  '/admin/timesheets': typeof AdminTimesheetsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/clients/new': typeof AdminClientsNewRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/resources/$id': typeof AdminResourcesIdRoute
  '/admin/resources/pending': typeof AdminResourcesPendingRoute
  '/admin/tasks/$id': typeof AdminTasksIdRoute
  '/admin/tasks/new': typeof AdminTasksNewRoute
  '/admin/clients/$id/edit': typeof AdminClientsIdEditRoute
  '/admin/projects/$id/edit': typeof AdminProjectsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/user': typeof UserRoute
  '/admin/clients': typeof AdminClientsRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/resources': typeof AdminResourcesRouteWithChildren
  '/admin/tasks': typeof AdminTasksRouteWithChildren
  '/admin/timesheets': typeof AdminTimesheetsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/clients/': typeof AdminClientsRoute
  '/admin/clients/new': typeof AdminClientsNewRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/resources/$id': typeof AdminResourcesIdRoute
  '/admin/resources/pending': typeof AdminResourcesPendingRoute
  '/admin/tasks/$id': typeof AdminTasksIdRoute
  '/admin/tasks/new': typeof AdminTasksNewRoute
  '/admin/clients/$id/edit': typeof AdminClientsIdEditRoute
  '/admin/projects/$id/edit': typeof AdminProjectsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/user'
    | '/admin/clients'
    | '/admin/profile'
    | '/admin/projects'
    | '/admin/resources'
    | '/admin/tasks'
    | '/admin/timesheets'
    | '/admin/'
    | '/admin/clients/'
    | '/admin/clients/new'
    | '/admin/projects/new'
    | '/admin/resources/$id'
    | '/admin/resources/pending'
    | '/admin/tasks/$id'
    | '/admin/tasks/new'
    | '/admin/clients/$id/edit'
    | '/admin/projects/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/user'
    | '/admin/profile'
    | '/admin/projects'
    | '/admin/resources'
    | '/admin/tasks'
    | '/admin/timesheets'
    | '/admin'
    | '/admin/clients'
    | '/admin/clients/new'
    | '/admin/projects/new'
    | '/admin/resources/$id'
    | '/admin/resources/pending'
    | '/admin/tasks/$id'
    | '/admin/tasks/new'
    | '/admin/clients/$id/edit'
    | '/admin/projects/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/user'
    | '/admin/clients'
    | '/admin/profile'
    | '/admin/projects'
    | '/admin/resources'
    | '/admin/tasks'
    | '/admin/timesheets'
    | '/admin/'
    | '/admin/clients/'
    | '/admin/clients/new'
    | '/admin/projects/new'
    | '/admin/resources/$id'
    | '/admin/resources/pending'
    | '/admin/tasks/$id'
    | '/admin/tasks/new'
    | '/admin/clients/$id/edit'
    | '/admin/projects/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  UserRoute: typeof UserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/timesheets': {
      id: '/admin/timesheets'
      path: '/timesheets'
      fullPath: '/admin/timesheets'
      preLoaderRoute: typeof AdminTimesheetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resources': {
      id: '/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AdminResourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tasks/new': {
      id: '/admin/tasks/new'
      path: '/new'
      fullPath: '/admin/tasks/new'
      preLoaderRoute: typeof AdminTasksNewRouteImport
      parentRoute: typeof AdminTasksRoute
    }
    '/admin/tasks/$id': {
      id: '/admin/tasks/$id'
      path: '/$id'
      fullPath: '/admin/tasks/$id'
      preLoaderRoute: typeof AdminTasksIdRouteImport
      parentRoute: typeof AdminTasksRoute
    }
    '/admin/resources/pending': {
      id: '/admin/resources/pending'
      path: '/pending'
      fullPath: '/admin/resources/pending'
      preLoaderRoute: typeof AdminResourcesPendingRouteImport
      parentRoute: typeof AdminResourcesRoute
    }
    '/admin/resources/$id': {
      id: '/admin/resources/$id'
      path: '/$id'
      fullPath: '/admin/resources/$id'
      preLoaderRoute: typeof AdminResourcesIdRouteImport
      parentRoute: typeof AdminResourcesRoute
    }
    '/admin/projects/new': {
      id: '/admin/projects/new'
      path: '/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AdminProjectsNewRouteImport
      parentRoute: typeof AdminProjectsRoute
    }
    '/admin/clients/new': {
      id: '/admin/clients/new'
      path: '/new'
      fullPath: '/admin/clients/new'
      preLoaderRoute: typeof AdminClientsNewRouteImport
      parentRoute: typeof AdminClientsRoute
    }
    '/admin/clients/': {
      id: '/admin/clients/'
      path: '/'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminClientsRoute
    }
    '/admin/projects/$id/edit': {
      id: '/admin/projects/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/projects/$id/edit'
      preLoaderRoute: typeof AdminProjectsIdEditRouteImport
      parentRoute: typeof AdminProjectsRoute
    }
    '/admin/clients/$id/edit': {
      id: '/admin/clients/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/clients/$id/edit'
      preLoaderRoute: typeof AdminClientsIdEditRouteImport
      parentRoute: typeof AdminClientsRoute
    }
  }
}

interface AdminClientsRouteChildren {
  AdminClientsRoute: typeof AdminClientsRoute
  AdminClientsNewRoute: typeof AdminClientsNewRoute
  AdminClientsIdEditRoute: typeof AdminClientsIdEditRoute
}

const AdminClientsRouteChildren: AdminClientsRouteChildren = {
  AdminClientsRoute: AdminClientsRoute,
  AdminClientsNewRoute: AdminClientsNewRoute,
  AdminClientsIdEditRoute: AdminClientsIdEditRoute,
}

const AdminClientsRouteWithChildren = AdminClientsRoute._addFileChildren(
  AdminClientsRouteChildren,
)

interface AdminProjectsRouteChildren {
  AdminProjectsNewRoute: typeof AdminProjectsNewRoute
  AdminProjectsIdEditRoute: typeof AdminProjectsIdEditRoute
}

const AdminProjectsRouteChildren: AdminProjectsRouteChildren = {
  AdminProjectsNewRoute: AdminProjectsNewRoute,
  AdminProjectsIdEditRoute: AdminProjectsIdEditRoute,
}

const AdminProjectsRouteWithChildren = AdminProjectsRoute._addFileChildren(
  AdminProjectsRouteChildren,
)

interface AdminResourcesRouteChildren {
  AdminResourcesIdRoute: typeof AdminResourcesIdRoute
  AdminResourcesPendingRoute: typeof AdminResourcesPendingRoute
}

const AdminResourcesRouteChildren: AdminResourcesRouteChildren = {
  AdminResourcesIdRoute: AdminResourcesIdRoute,
  AdminResourcesPendingRoute: AdminResourcesPendingRoute,
}

const AdminResourcesRouteWithChildren = AdminResourcesRoute._addFileChildren(
  AdminResourcesRouteChildren,
)

interface AdminTasksRouteChildren {
  AdminTasksIdRoute: typeof AdminTasksIdRoute
  AdminTasksNewRoute: typeof AdminTasksNewRoute
}

const AdminTasksRouteChildren: AdminTasksRouteChildren = {
  AdminTasksIdRoute: AdminTasksIdRoute,
  AdminTasksNewRoute: AdminTasksNewRoute,
}

const AdminTasksRouteWithChildren = AdminTasksRoute._addFileChildren(
  AdminTasksRouteChildren,
)

interface AdminRouteChildren {
  AdminClientsRoute: typeof AdminClientsRouteWithChildren
  AdminProfileRoute: typeof AdminProfileRoute
  AdminProjectsRoute: typeof AdminProjectsRouteWithChildren
  AdminResourcesRoute: typeof AdminResourcesRouteWithChildren
  AdminTasksRoute: typeof AdminTasksRouteWithChildren
  AdminTimesheetsRoute: typeof AdminTimesheetsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClientsRoute: AdminClientsRouteWithChildren,
  AdminProfileRoute: AdminProfileRoute,
  AdminProjectsRoute: AdminProjectsRouteWithChildren,
  AdminResourcesRoute: AdminResourcesRouteWithChildren,
  AdminTasksRoute: AdminTasksRouteWithChildren,
  AdminTimesheetsRoute: AdminTimesheetsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  UserRoute: UserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
